<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Omnitags extends CI_Controller
{
    public $head = '_partials/head';

    // Di bawah ini adalah fungsi config
    public $file_type1 = 'png|jpg|jpeg';
    public $file_type2 = 'pdf';

    // Di bawah ini adalah bagian part dari views
    public $v_part1 = 'title';
    public $v_part2 = 'head';
    public $v_part3 = 'konten';
    public $v_part4 = 'phase';
    public $v_part5 = 'dekor';
    public $v_part4_msg0 = '<br><span class="h6"> (phase pre-alpha feature)</span>';
    public $v_part4_msg1 = '<br><span class="h6"> (phase alpha feature)</span>';
    public $v_part4_msg2 = '<br><span class="h6"> (phase beta feature)</span>';
    public $v_part4_msg3 = '<br><span class="h6"> (release candidate feature)</span>';
    public $v_part4_msg4 = '';  // feature released


    public $aliases;
    public $views;
    public $flashdatas;
    public $parts;

    public function declarew()
    {

        $jsonData = file_get_contents(site_url('assets/json/school_ukk_spp.postman_environment.json'));
        $myData = json_decode($jsonData, true)['values'];

        // Create variables dynamically
        foreach ($myData as $item) {
            ${$item['key']} = $item['value']; // Variable variable to create dynamic variables
        }

        $this->aliases = array(
            // 'tabel1' => $tabel1,
            // 'tabel1_alias' => $tabel1_alias,
            // 'tabel1_field1' => $tabel1_field1,
            // 'tabel1_field1_alias' => $tabel1_field1_alias,
            // 'tabel1_field2' => $tabel1_field2,
            // 'tabel1_field2_alias' => $tabel1_field2_alias,
            // 'tabel1_field3' => $tabel1_field3,
            // 'tabel1_field3_alias' => $tabel1_field3_alias,
            // 'tabel1_field4' => $tabel1_field4,
            // 'tabel1_field4_alias' => $tabel1_field4_alias,

            // 'tabel2' => $tabel2,
            // 'tabel2_alias' => $tabel2_alias,
            // 'tabel2_field1' => $tabel2_field1,
            // 'tabel2_field1_alias' => $tabel2_field1_alias,
            // 'tabel2_field2' => $tabel2_field2,
            // 'tabel2_field2_alias' => $tabel2_field2_alias,
            // 'tabel2_field3' => $tabel2_field3,
            // 'tabel2_field3_alias' => $tabel2_field3_alias,
            // 'tabel2_field4' => $tabel2_field4,
            // 'tabel2_field4_alias' => $tabel2_field4_alias,
            // 'tabel2_field5' => $tabel2_field5,
            // 'tabel2_field5_alias' => $tabel2_field5_alias,
            // 'tabel2_field6' => $tabel2_field6,
            // 'tabel2_field6_alias' => $tabel2_field6_alias,
            // 'tabel2_field7' => $tabel2_field7,
            // 'tabel2_field7_alias' => $tabel2_field7_alias,
            // 'tabel2_field8' => $tabel2_field8,
            // 'tabel2_field8_alias' => $tabel2_field8_alias,
            // 'tabel2_field9' => $tabel2_field9,
            // 'tabel2_field9_alias' => $tabel2_field9_alias,
            // 'tabel2_field10' => $tabel2_field10,
            // 'tabel2_field10_alias' => $tabel2_field10_alias,
            // 'tabel2_field11' => $tabel2_field11,
            // 'tabel2_field11_alias' => $tabel2_field11_alias,
            // 'tabel2_field12' => $tabel2_field12,
            // 'tabel2_field12_alias' => $tabel2_field12_alias,
            // 'tabel2_field13' => $tabel2_field13,
            // 'tabel2_field13_alias' => $tabel2_field13_alias,
            // 'tabel2_field14' => $tabel2_field14,
            // 'tabel2_field14_alias' => $tabel2_field14_alias,
            // 'tabel2_field15' => $tabel2_field15,
            // 'tabel2_field15_alias' => $tabel2_field15_alias,

            // 'tabel3' => $tabel3,
            // 'tabel3_alias' => $tabel3_alias,
            // 'tabel3_field1' => $tabel3_field1,
            // 'tabel3_field1_alias' => $tabel3_field1_alias,
            // 'tabel3_field2' => $tabel3_field2,
            // 'tabel3_field2_alias' => $tabel3_field2_alias,
            // 'tabel3_field3' => $tabel3_field3,
            // 'tabel3_field3_alias' => $tabel3_field3_alias,
            // 'tabel3_field4' => $tabel3_field4,
            // 'tabel3_field4_alias' => $tabel3_field4_alias,

            'tabel4' => $tabel4,
            'tabel4_alias' => $tabel4_alias,
            'tabel4_field1' => $tabel4_field1,
            'tabel4_field1_alias' => $tabel4_field1_alias,
            'tabel4_field2' => $tabel4_field2,
            'tabel4_field2_alias' => $tabel4_field2_alias,
            'tabel4_field3' => $tabel4_field3,
            'tabel4_field3_alias' => $tabel4_field3_alias,
            'tabel4_field4' => $tabel4_field4,
            'tabel4_field4_alias' => $tabel4_field4_alias,
            'tabel4_field5' => $tabel4_field5,
            'tabel4_field5_alias' => $tabel4_field5_alias,
            'tabel4_field6' => $tabel4_field6,
            'tabel4_field6_alias' => $tabel4_field6_alias,
            'tabel4_field7' => $tabel4_field7,
            'tabel4_field7_alias' => $tabel4_field7_alias,
            'tabel4_field8' => $tabel4_field8,
            'tabel4_field8_alias' => $tabel4_field8_alias,
            'tabel4_field9' => $tabel4_field9,
            'tabel4_field9_alias' => $tabel4_field9_alias,
            'tabel4_field9_value1' => $tabel4_field9_value1,
            'tabel4_field9_value1_alias' => $tabel4_field9_value1_alias,
            'tabel4_field9_value2' => $tabel4_field9_value1,
            'tabel4_field9_value2_alias' => $tabel4_field9_value2_alias,

            'tabel5' => $tabel5,
            'tabel5_alias' => $tabel5_alias,
            'tabel5_field1' => $tabel5_field1,
            'tabel5_field1_alias' => $tabel5_field1_alias,
            'tabel5_field2' => $tabel5_field2,
            'tabel5_field2_alias' => $tabel5_field2_alias,
            'tabel5_field3' => $tabel5_field3,
            'tabel5_field3_alias' => $tabel5_field3_alias,

            'tabel6' => $tabel6,
            'tabel6_alias' => $tabel6_alias,
            'tabel6_field1' => $tabel6_field1,
            'tabel6_field1_alias' => $tabel6_field1_alias,
            'tabel6_field2' => $tabel6_field2,
            'tabel6_field2_alias' => $tabel6_field2_alias,
            'tabel6_field3' => $tabel6_field3,
            'tabel6_field3_alias' => $tabel6_field3_alias,

            'tabel7' => $tabel7,
            'tabel7_alias' => $tabel7_alias,
            'tabel7_field1' => $tabel7_field1,
            'tabel7_field1_alias' => $tabel7_field1_alias,
            'tabel7_field2' => $tabel7_field2,
            'tabel7_field2_alias' => $tabel7_field2_alias,
            'tabel7_field3' => $tabel7_field3,
            'tabel7_field3_alias' => $tabel7_field3_alias,
            'tabel7_field4' => $tabel7_field4,
            'tabel7_field4_alias' => $tabel7_field4_alias,
            'tabel7_field5' => $tabel7_field5,
            'tabel7_field5_alias' => $tabel7_field5_alias,
            'tabel7_field6' => $tabel7_field6,
            'tabel7_field6_alias' => $tabel7_field6_alias,
            'tabel7_field7' => $tabel7_field7,
            'tabel7_field7_alias' => $tabel7_field7_alias,
            'tabel7_field8' => $tabel7_field8,
            'tabel7_field8_alias' => $tabel7_field8_alias,
            'tabel7_field9' => $tabel7_field9,
            'tabel7_field9_alias' => $tabel7_field9_alias,
            'tabel7_field10' => $tabel7_field10,
            'tabel7_field10_alias' => $tabel7_field10_alias,
            'tabel7_field11' => $tabel7_field11,
            'tabel7_field11_alias' => $tabel7_field11_alias,
            'tabel7_field12' => $tabel7_field12,
            'tabel7_field12_alias' => $tabel7_field12_alias,

            'tabel8' => $tabel8,
            'tabel8_alias' => $tabel8_alias,
            'tabel8_field1' => $tabel8_field1,
            'tabel8_field1_alias' => $tabel8_field1_alias,
            'tabel8_field2' => $tabel8_field2,
            'tabel8_field2_alias' => $tabel8_field2_alias,
            'tabel8_field3' => $tabel8_field3,
            'tabel8_field3_alias' => $tabel8_field3_alias,
            'tabel8_field4' => $tabel8_field4,
            'tabel8_field4_alias' => $tabel8_field4_alias,
            'tabel8_field5' => $tabel8_field5,
            'tabel8_field5_alias' => $tabel8_field5_alias,
            'tabel8_field6' => $tabel8_field6,
            'tabel8_field6_alias' => $tabel8_field6_alias,
            'tabel8_field7' => $tabel8_field7,
            'tabel8_field7_alias' => $tabel8_field7_alias,
            'tabel8_field8' => $tabel8_field8,
            'tabel8_field8_alias' => $tabel8_field8_alias,

            'tabel9' => $tabel9,
            'tabel9_alias' => $tabel9_alias,
            'tabel9_field1' => $tabel9_field1,
            'tabel9_field1_alias' => $tabel9_field1_alias,
            'tabel9_field2' => $tabel9_field2,
            'tabel9_field2_alias' => $tabel9_field2_alias,
            'tabel9_field3' => $tabel9_field3,
            'tabel9_field3_alias' => $tabel9_field3_alias,
            'tabel9_field4' => $tabel9_field4,
            'tabel9_field4_alias' => $tabel9_field4_alias,
            'tabel9_field5' => $tabel9_field5,
            'tabel9_field5_alias' => $tabel9_field5_alias,
            'tabel9_field6' => $tabel9_field6,
            'tabel9_field6_alias' => $tabel9_field6_alias,
            'tabel9_field6_value1' => $tabel9_field6_value1,

            'tabel9_field6_value2' => $tabel9_field6_value2,
            'tabel9_field6_value2_alias' => $tabel9_field6_value2_alias,

            'tabel9_field6_value3' => $tabel9_field6_value3,
            'tabel9_field6_value3_alias' => $tabel9_field6_value3_alias,

            'tabel9_field6_value4' => $tabel9_field6_value4,
            'tabel9_field6_value4_alias' => $tabel9_field6_value4_alias,

            'tabel9_field6_value5' => $tabel9_field6_value5,
            'tabel9_field6_value5_alias' => $tabel9_field6_value5_alias,

            'tabel9_field7' => $tabel9_field7,
            'tabel9_field7_alias' => $tabel9_field7_alias,

            // 'tabel10' => $tabel10,
            // 'tabel10_alias' => $tabel10_alias,
            // 'tabel10_field1' => $tabel10_field1,
            // 'tabel10_field1_alias' => $tabel10_field1_alias,
            // 'tabel10_field2' => $tabel10_field2,
            // 'tabel10_field2_alias' => $tabel10_field2_alias,
            // 'tabel10_field3' => $tabel10_field3,
            // 'tabel10_field3_alias' => $tabel10_field3_alias,
            // 'tabel10_field4' => $tabel10_field4,
            // 'tabel10_field4_alias' => $tabel10_field4_alias,
            // 'tabel10_field5' => $tabel10_field5,
            // 'tabel10_field5_alias' => $tabel10_field5_alias,

            // 'tabel10_field5_value1' => $tabel10_field5_value1,
            // 'tabel10_field5_value1_alias' => $tabel10_field5_value1_alias,
            // 'tabel10_field5_value2' => $tabel10_field5_value2,
            // 'tabel10_field5_value2_alias' => $tabel10_field5_value2_alias,


            // 'tabel10_field6' => $tabel10_field6,
            // 'tabel10_field6_alias' => $tabel10_field6_alias,
            // 'tabel10_field7' => $tabel10_field7,
            // 'tabel10_field7_alias' => $tabel10_field7_alias,

            // 'tabel11' => $tabel11,
            // 'tabel11_alias' => $tabel11_alias,
            // 'tabel11_field1' => $tabel11_field1,
            // 'tabel11_field1_alias' => $tabel11_field1_alias,
            // 'tabel11_field2' => $tabel11_field2,
            // 'tabel11_field2_alias' => $tabel11_field2_alias,
            // 'tabel11_field3' => $tabel11_field3,
            // 'tabel11_field3_alias' => $tabel11_field3_alias,
            // 'tabel11_field4' => $tabel11_field4,
            // 'tabel11_field4_alias' => $tabel11_field4_alias,
            // 'tabel11_field5' => $tabel11_field5,
            // 'tabel11_field5_alias' => $tabel11_field5_alias,
            // 'tabel11_field6' => $tabel11_field6,
            // 'tabel11_field6_alias' => $tabel11_field6_alias,
            // 'tabel11_field7' => $tabel11_field7,
            // 'tabel11_field7_alias' => $tabel11_field7_alias,

            'tabel12' => $tabel12,
            'tabel12_alias' => $tabel12_alias,
            'tabel12_field1' => $tabel12_field1,
            'tabel12_field1_alias' => $tabel12_field1_alias,
            'tabel12_field2' => $tabel12_field2,
            'tabel12_field2_alias' => $tabel12_field2_alias,
            'tabel12_field3' => $tabel12_field3,
            'tabel12_field3_alias' => $tabel12_field3_alias,
            'tabel12_field4' => $tabel12_field4,
            'tabel12_field4_alias' => $tabel12_field4_alias,

            'tabel13' => $tabel13,
            'tabel13_alias' => $tabel13_alias,
            'tabel13_field1' => $tabel13_field1,
            'tabel13_field1_alias' => $tabel13_field1_alias,
            'tabel13_field2' => $tabel13_field2,
            'tabel13_field2_alias' => $tabel13_field2_alias,
            'tabel13_field3' => $tabel13_field3,
            'tabel13_field3_alias' => $tabel13_field3_alias,
            'tabel13_field4' => $tabel13_field4,
            'tabel13_field4_alias' => $tabel13_field4_alias,
            'tabel13_field5' => $tabel13_field5,
            'tabel13_field5_alias' => $tabel13_field5_alias,


            'year_code' => '@2020-2024',
            'copyright_notices' => 'All Rights Reserved.'
        );

        $this->views = array(
            'v1' => '_layouts/template',
            'v1_title' => '',
            'v2' => 'login',
            'v2_title' => 'Login',
            'v3' => 'signup',
            'v3_title' => 'Sign Up',
            'v4' => 'no-level',
            'v4_title' => 'Anda tidak memiliki akses ke halaman ini!',
            'v5' => 'dashboard',
            'v5_title' => 'Dashboard',
            'v6' => 'home',
            'v6_title' => 'Selamat Datang',



            // 'tabel1_v1' => '_contents/tabel1/index',
            // 'tabel1_v1_title' => 'Daftar ' . $tabel1_alias,
            // 'tabel1_v2' => '_contents/tabel1/admin',
            // 'tabel1_v2_title' => 'Data ' . $tabel1_alias,
            // 'tabel1_v3' => '_contents/tabel1/print',
            // 'tabel1_v3_title' => 'Laporan ' . $tabel1_alias,

            // 'tabel1_v_input1' => $tabel1_field1,
            // 'tabel1_v_input1_post' => $this->input->post($tabel1_field1),
            // 'tabel1_v_input1_alt' => '',
            // 'tabel1_v_input2' => $tabel1_field2,
            // 'tabel1_v_input2_post' => $this->input->post($tabel1_field2),
            // 'tabel1_v_input3' => $tabel1_field3,
            // 'tabel1_v_input3_post' => $this->input->post($tabel1_field3),



            // 'tabel2_v1' => '_contents/tabel2/index',
            // 'tabel2_v1_title' => 'Daftar ' . $tabel2_alias,
            // 'tabel2_v2' => '_contents/tabel2/admin',
            // 'tabel2_v2_title' => 'Data ' . $tabel2_alias,
            // 'tabel2_v3' => '_contents/tabel2/print',
            // 'tabel2_v3_title' => 'Laporan ' . $tabel2_alias,
            // 'tabel2_v4' => '_contents/tabel2/receipt',
            // 'tabel2_v4_title' => 'Bukti ' . $tabel2_alias,

            // 'tabel2_v_input1' => $tabel2_field1,
            // 'tabel2_v_input1_post' => $this->input->post($tabel2_field1),
            // 'tabel2_v_input1_alt' => '',
            // 'tabel2_v_input2' => $tabel2_field2,
            // 'tabel2_v_input2_post' => $this->input->post($tabel2_field2),
            // 'tabel2_v_input3' => $tabel2_field3,
            // 'tabel2_v_input3_post' => $this->input->post($tabel2_field3),
            // 'tabel2_v_input4' => $tabel2_field4,
            // 'tabel2_v_input4_post' => $this->input->post($tabel2_field4),
            // 'tabel2_v_input5' => $tabel2_field5,
            // 'tabel2_v_input5_post' => $this->input->post($tabel2_field5),
            // 'tabel2_v_input6' => $tabel2_field6,
            // 'tabel2_v_input6_post' => $this->input->post($tabel2_field6),
            // 'tabel2_v_input7' => $tabel2_field7,
            // 'tabel2_v_input7_post' => $this->input->post($tabel2_field7),
            // 'tabel2_v_input8' => $tabel2_field8,
            // 'tabel2_v_input8_post' => $this->input->post($tabel2_field8),
            // 'tabel2_v_input9' => $tabel2_field9,
            // 'tabel2_v_input9_post' => $this->input->post($tabel2_field9),
            // 'tabel2_v_input10' => $tabel2_field10,
            // 'tabel2_v_input10_post' => $this->input->post($tabel2_field10),
            // 'tabel2_v_input11' => $tabel2_field11,
            // 'tabel2_v_input11_post' => $this->input->post($tabel2_field11),
            // 'tabel2_v_input11_filter1' => $tabel2_field11 . '_min',
            // 'tabel2_v_input11_filter1_get' => $this->input->get($tabel2_field11 . '_min'),
            // 'tabel2_v_input11_filter2' => $tabel2_field11 . '_max',
            // 'tabel2_v_input11_filter2_get' => $this->input->get($tabel2_field11 . '_max'),
            // 'tabel2_v_input12' => $tabel2_field12,
            // 'tabel2_v_input12_post' => $this->input->post($tabel2_field12),
            // 'tabel2_v_input12_filter1' => $tabel2_field12 . '_min',
            // 'tabel2_v_input12_filter1_get' => $this->input->get($tabel2_field12 . '_min'),
            // 'tabel2_v_input12_filter2' => $tabel2_field12 . '_max',
            // 'tabel2_v_input12_filter2_get' => $this->input->get($tabel2_field12 . '_max'),
            // 'tabel2_v_input13' => $tabel2_field13,
            // 'tabel2_v_input13_post' => $this->input->post($tabel2_field13),
            // 'tabel2_v_input14' => $tabel2_field14,
            // 'tabel2_v_input14_post' => $this->input->post($tabel2_field14),
            // 'tabel2_v_input15' => $tabel2_field15,
            // 'tabel2_v_input15_post' => $this->input->post($tabel2_field15),



            // 'tabel3_v1' => '_contents/tabel3/index',
            // 'tabel3_v1_title' => 'Daftar ' . $tabel3_alias,
            // 'tabel3_v2' => '_contents/tabel3/admin',
            // 'tabel3_v2_title' => 'Data ' . $tabel3_alias,
            // 'tabel3_v3' => '_contents/tabel3/print',
            // 'tabel3_v3_title' => 'Laporan ' . $tabel3_alias,

            // 'tabel3_v_input1' => $tabel3_field1,
            // 'tabel3_v_input1_post' => $this->input->post($tabel3_field1),
            // 'tabel3_v_input1_alt' => '',
            // 'tabel3_v_input2' => $tabel3_field2,
            // 'tabel3_v_input2_post' => $this->input->post($tabel3_field2),
            // 'tabel3_v_input3' => $tabel3_field3,
            // 'tabel3_v_input3_post' => $this->input->post($tabel3_field3),



            'tabel4_v1' => '_contents/tabel4/index',
            'tabel4_v1_title' => 'Daftar ' . $tabel4_alias,
            'tabel4_v2' => '_contents/tabel4/admin',
            'tabel4_v2_title' => 'Data ' . $tabel4_alias,
            'tabel4_v3' => '_contents/tabel4/print',
            'tabel4_v3_title' => 'Laporan ' . $tabel4_alias,
            'tabel4_v4' => '_contents/tabel4/login',
            'tabel4_v4_title' => 'Login Sebagai ' . $tabel4_alias,

            'tabel4_v_input1' => $tabel4_field1,
            'tabel4_v_input1_post' => $this->input->post($tabel4_field1),
            'tabel4_v_input1_alt' => '',
            'tabel4_v_input2' => $tabel4_field2,
            'tabel4_v_input2_post' => $this->input->post($tabel4_field2),
            'tabel4_v_input3' => $tabel4_field3,
            'tabel4_v_input3_post' => $this->input->post($tabel4_field3),
            'tabel4_v_input4' => $tabel4_field4,
            'tabel4_v_input4_post' => $this->input->post($tabel4_field4),
            'tabel4_v_input5' => $tabel4_field5,
            'tabel4_v_input5_post' => $this->input->post($tabel4_field5),
            'tabel4_v_input6' => $tabel4_field6,
            'tabel4_v_input6_post' => $this->input->post($tabel4_field6),
            'tabel4_v_input7' => $tabel4_field7,
            'tabel4_v_input7_post' => $this->input->post($tabel4_field7),
            'tabel4_v_input8' => $tabel4_field8,
            'tabel4_v_input8_post' => $this->input->post($tabel4_field8),
            'tabel4_v_input9' => $tabel4_field9,
            'tabel4_v_input9_post' => $this->input->post($tabel4_field9),

            'tabel5_v1' => '_contents/tabel5/index',
            'tabel5_v1_title' => 'Daftar ' . $tabel5_alias,
            'tabel5_v2' => '_contents/tabel5/admin',
            'tabel5_v2_title' => 'Data ' . $tabel5_alias,
            'tabel5_v3' => '_contents/tabel5/print',
            'tabel5_v3_title' => 'Laporan ' . $tabel5_alias,

            'tabel5_v_input1' => $tabel5_field1,
            'tabel5_v_input1_post' => $this->input->post($tabel5_field1),
            'tabel5_v_input1_alt' => '',
            'tabel5_v_input2' => $tabel5_field2,
            'tabel5_v_input2_post' => $this->input->post($tabel5_field2),
            'tabel5_v_input3' => $tabel5_field3,
            'tabel5_v_input3_post' => $this->input->post($tabel5_field3),


            'tabel6_v1' => '_contents/tabel6/index',
            'tabel6_v1_title' => 'Daftar ' . $tabel6_alias,
            'tabel6_v2' => '_contents/tabel6/admin',
            'tabel6_v2_title' => 'Data ' . $tabel6_alias,
            'tabel6_v3' => '_contents/tabel6/print',
            'tabel6_v3_title' => 'Laporan ' . $tabel6_alias,

            'tabel6_v_input1' => $tabel6_field1,
            'tabel6_v_input1_post' => $this->input->post($tabel6_field1),
            'tabel6_v_input1_alt' => '',
            'tabel6_v_input2' => $tabel6_field2,
            'tabel6_v_input2_post' => $this->input->post($tabel6_field2),
            'tabel6_v_input3' => $tabel6_field3,
            'tabel6_v_input3_post' => $this->input->post($tabel6_field3),



            'tabel7_v1' => '_contents/tabel7/index',
            'tabel7_v1_title' => 'Daftar ' . $tabel7_alias,
            'tabel7_v2' => '_contents/tabel7/admin',
            'tabel7_v2_title' => 'Data ' . $tabel7_alias,
            'tabel7_v3' => '_contents/tabel7/print',
            'tabel7_v3_title' => 'Laporan ' . $tabel7_alias,

            'tabel7_v_input1' => $tabel7_field1,
            'tabel7_v_input1_post' => $this->input->post($tabel7_field1),
            'tabel7_v_input1_alt' => '',
            'tabel7_v_input2' => $tabel7_field2,
            'tabel7_v_input2_post' => $this->input->post($tabel7_field2),
            'tabel7_v_input3' => $tabel7_field3,
            'tabel7_v_input3_upload_path' => './assets/img/tabel7/',
            'tabel7_v_input3_post' => $this->input->post($tabel7_field3),
            'tabel7_v_input3_alt' => $this->input->post('txt' . $tabel7_field3),
            'tabel7_v_input4' => $tabel7_field4,
            'tabel7_v_input4_upload_path' => './assets/img/tabel7/',
            'tabel7_v_input4_post' => $this->input->post($tabel7_field4),
            'tabel7_v_input4_alt' => $this->input->post('txt' . $tabel7_field4),
            'tabel7_v_input5' => $tabel7_field5,
            'tabel7_v_input5_upload_path' => './assets/img/tabel7/',
            'tabel7_v_input5_post' => $this->input->post($tabel7_field5),
            'tabel7_v_input5_alt' => $this->input->post('txt' . $tabel7_field5),
            'tabel7_v_input6' => $tabel7_field6,
            'tabel7_v_input6_post' => $this->input->post($tabel7_field6),
            'tabel7_v_input7' => $tabel7_field7,
            'tabel7_v_input7_post' => $this->input->post($tabel7_field7),
            'tabel7_v_input8' => $tabel7_field8,
            'tabel7_v_input8_post' => $this->input->post($tabel7_field8),
            'tabel7_v_input9' => $tabel7_field9,
            'tabel7_v_input9_post' => $this->input->post($tabel7_field9),
            'tabel7_v_input10' => $tabel7_field10,
            'tabel7_v_input10_post' => $this->input->post($tabel7_field10),
            'tabel7_v_input11' => $tabel7_field11,
            'tabel7_v_input11_post' => $this->input->post($tabel7_field11),
            'tabel7_v_input12' => $tabel7_field12,
            'tabel7_v_input12_post' => $this->input->post($tabel7_field12),



            'tabel8_v1' => '_contents/tabel8/index',
            'tabel8_v1_title' => 'Daftar ' . $tabel8_alias,
            'tabel8_v2' => '_contents/tabel8/admin',
            'tabel8_v2_title' => 'Data ' . $tabel8_alias,
            'tabel8_v3' => '_contents/tabel8/print',
            'tabel8_v3_title' => 'Laporan ' . $tabel8_alias,
            'tabel8_v4' => '_contents/tabel8/receipt',
            'tabel8_v4_title' => 'Bukti ' . $tabel8_alias,
            'tabel8_v5' => '_contents/tabel8/cari',
            'tabel8_v5_title' => 'Daftar ' . $tabel8_alias,
            'tabel8_v6' => '_contents/tabel8/pesan',
            'tabel8_v6_title' => 'Daftarkan ' . $tabel8_alias,
            'tabel8_v7' => '_contents/tabel8/konfirmasi',
            'tabel8_v7_title' => $tabel8_alias . ' Berhasil',

            'tabel8_v_input1' => $tabel8_field1,
            'tabel8_v_input1_post' => $this->input->post($tabel8_field1),
            'tabel8_v_input1_get' => $this->input->get($tabel8_field1),
            'tabel8_v_input1_alt' => '',
            'tabel8_v_input2_post' => $this->input->post($tabel8_field2),
            'tabel8_v_input2_get' => $this->input->get($tabel8_field2),
            'tabel8_v_input2' => $tabel8_field2,
            'tabel8_v_input3' => $tabel8_field3,
            'tabel8_v_input3_post' => $this->input->post($tabel8_field3),
            'tabel8_v_input4' => $tabel8_field4,
            'tabel8_v_input4_post' => $this->input->post($tabel8_field4),
            'tabel8_v_input4_get' => $this->input->get($tabel8_field4),
            'tabel8_v_input5' => $tabel8_field5,
            'tabel8_v_input5_post' => $this->input->post($tabel8_field5),
            'tabel8_v_input6' => $tabel8_field6,
            'tabel8_v_input6_post' => $this->input->post($tabel8_field6),
            'tabel8_v_input7' => $tabel8_field7,
            'tabel8_v_input7_post' => $this->input->post($tabel8_field7),
            'tabel8_v_input8' => $tabel8_field8,
            'tabel8_v_input8_post' => $this->input->post($tabel8_field8),
            'tabel8_v_input8_get' => $this->input->get($tabel8_field8),



            'tabel9_v1' => '_contents/tabel9/index',
            'tabel9_v1_title' => 'Daftar ' . $tabel9_alias,
            'tabel9_v2' => '_contents/tabel9/admin',
            'tabel9_v2_title' => 'Data ' . $tabel9_alias,
            'tabel9_v3' => '_contents/tabel9/print',
            'tabel9_v3_title' => 'Data ' . $tabel9_alias,

            'tabel9_v_input1' => $tabel9_field1,
            'tabel9_v_input1_post' => $this->input->post($tabel9_field1),
            'tabel9_v_input1_alt' => '',
            'tabel9_v_input2' => $tabel9_field2,
            'tabel9_v_input2_post' => $this->input->post($tabel9_field2),
            'tabel9_v_input3' => $tabel9_field3,
            'tabel9_v_input3_post' => $this->input->post($tabel9_field3),
            'tabel9_v_input4_old' => 'old_' . $tabel9_field4,
            'tabel9_v_input4_old_post' => $this->input->post('old_' . $tabel9_field4),
            'tabel9_v_input4' => $tabel9_field4,
            'tabel9_v_input4_post' => $this->input->post($tabel9_field4),
            'tabel9_v_input5' => $tabel9_field5,
            'tabel9_v_input5_post' => $this->input->post($tabel9_field5),
            'tabel9_v_input6' => $tabel9_field6,
            'tabel9_v_input6_post' => $this->input->post($tabel9_field6),
            'tabel9_v_input7' => $tabel9_field7,
            'tabel9_v_input7_post' => $this->input->post($tabel9_field7),



            // 'tabel10_v1' => '_contents/tabel10/index',
            // 'tabel10_v1_title' => 'Daftar ' . $tabel10_alias,
            // 'tabel10_v1_alt' => '_contents/tabel10/tabel2',
            // 'tabel10_v1_alt_title' => 'Daftar ' . $tabel10_alias . $tabel2_alias,
            // 'tabel10_v2' => '_contents/tabel10/admin',
            // 'tabel10_v2_title' => 'Data ' . $tabel10_alias,
            // 'tabel10_v2_alt' => '_contents/tabel10/admin_tabel2',
            // 'tabel10_v2_alt_title' => 'Data ' . $tabel10_alias . $tabel2_alias,
            // 'tabel10_v3' => '_contents/tabel10/print',
            // 'tabel10_v3_title' => 'Laporan ' . $tabel10_alias,
            // 'tabel10_v4' => '_contents/tabel10/receipt',
            // 'tabel10_v4_title' => 'Bukti ' . $tabel10_alias,
            // 'tabel10_v5' => '_contents/tabel8/konfirmasi',
            // 'tabel10_v5_title' => $tabel10_alias . ' Berhasil',

            // 'tabel10_v_input1' => $tabel10_field1,
            // 'tabel10_v_input1_post' => $this->input->post($tabel10_field1),
            // 'tabel10_v_input1_alt' => '',
            // 'tabel10_v_input2' => $tabel10_field2,
            // 'tabel10_v_input2_post' => $this->input->post($tabel10_field2),
            // 'tabel10_v_input3' => $tabel10_field3,
            // 'tabel10_v_input3_post' => $this->input->post($tabel10_field3),
            // 'tabel10_v_input4' => $tabel10_field4,
            // 'tabel10_v_input4_post' => $this->input->post($tabel10_field4),
            // 'tabel10_v_input5' => $tabel10_field5,
            // 'tabel10_v_input5_post' => $this->input->post($tabel10_field5),
            // 'tabel10_v_input6' => $tabel10_field6,
            // 'tabel10_v_input6_post' => $this->input->post($tabel10_field6),
            // 'tabel10_v_input7' => $tabel10_field7,
            // 'tabel10_v_input7_post' => $this->input->post($tabel10_field7),
            // 'tabel10_v_input7_filter1' => $tabel10_field7 . '_min',
            // 'tabel10_v_input7_filter1_get' => $this->input->get($tabel10_field7 . '_min'),
            // 'tabel10_v_input7_filter2' => $tabel10_field7 . '_max',
            // 'tabel10_v_input7_filter2_get' => $this->input->get($tabel10_field7 . '_max'),



            // 'tabel11_v1' => '_contents/tabel11/index',
            // 'tabel11_v1_title' => 'Daftar ' . $tabel11_alias,
            // 'tabel11_v2' => '_contents/tabel11/admin',
            // 'tabel11_v2_title' => 'Data ' . $tabel11_alias,
            // 'tabel11_v3' => '_contents/tabel11/print',
            // 'tabel11_v3_title' => 'Laporan ' . $tabel11_alias,

            // 'tabel11_v_input1' => $tabel11_field1,
            // 'tabel11_v_input1_post' => $this->input->post($tabel11_field1),
            // 'tabel11_v_input1_alt' => '',
            // 'tabel11_v_input2' => $tabel11_field2,
            // 'tabel11_v_input2_post' => $this->input->post($tabel11_field2),
            // 'tabel11_v_input3' => $tabel11_field3,
            // 'tabel11_v_input3_post' => $this->input->post($tabel11_field3),
            // 'tabel11_v_input4' => $tabel11_field4,
            // 'tabel11_v_input4_post' => $this->input->post($tabel11_field4),
            // 'tabel11_v_input5' => $tabel11_field5,
            // 'tabel11_v_input5_post' => $this->input->post($tabel11_field5),
            // 'tabel11_v_input6' => $tabel11_field6,
            // 'tabel11_v_input6_post' => $this->input->post($tabel11_field6),



            'tabel12_v1' => '_contents/tabel12/index',
            'tabel12_v1_title' => 'Daftar ' . $tabel12_alias,
            'tabel12_v2' => '_contents/tabel12/admin',
            'tabel12_v2_title' => 'Data ' . $tabel12_alias,
            'tabel12_v3' => '_contents/tabel12/print',
            'tabel12_v3_title' => 'Laporan ' . $tabel12_alias,

            'tabel12_v_input1' => $tabel12_field1,
            'tabel12_v_input1_post' => $this->input->post($tabel12_field1),
            'tabel12_v_input1_alt' => '',
            'tabel12_v_input2' => $tabel12_field2,
            'tabel12_v_input2_post' => $this->input->post($tabel12_field2),
            'tabel12_v_input3' => $tabel12_field3,
            'tabel12_v_input3_upload_path' => './assets/img/tabel12/',
            'tabel12_v_input3_post' => $this->input->post($tabel12_field3),
            'tabel12_v_input3_alt' => $this->input->post('txt' . $tabel12_field3),
            'tabel12_v_input4' => $tabel12_field4,
            'tabel12_v_input4_post' => $this->input->post($tabel12_field4),



            'tabel13_v1' => '_contents/tabel13/index',
            'tabel13_v1_title' => 'Daftar ' . $tabel13_alias,
            'tabel13_v2' => '_contents/tabel13/admin',
            'tabel13_v2_title' => 'Data ' . $tabel13_alias,
            'tabel13_v3' => '_contents/tabel13/print',
            'tabel13_v3_title' => 'Laporan ' . $tabel13_alias,

            'tabel13_v_input1' => $tabel13_field1,
            'tabel13_v_input1_post' => $this->input->post($tabel13_field1),
            'tabel13_v_input1_alt' => '',
            'tabel13_v_input2' => $tabel13_field2,
            'tabel13_v_input2_post' => $this->input->post($tabel13_field2),
            'tabel13_v_input3' => $tabel13_field3,
            'tabel13_v_input3_post' => $this->input->post($tabel13_field3),
            'tabel13_v_input4' => $tabel13_field4,
            'tabel13_v_input4_upload_path' => './assets/img/tabel13/',
            'tabel13_v_input4_post' => $this->input->post($tabel13_field4),
            'tabel13_v_input4_alt' => $this->input->post('txt' . $tabel13_field4),
            'tabel13_v_input5' => $tabel13_field5,
            'tabel13_v_input5_post' => $this->input->post($tabel13_field5),
        );

        $this->flashdatas = array(
            // deklarasi flashdata
            // Flashdata di sini bertugas untuk menemani pengguna dalam perselancarannya di website ini
            // Elemen yang digunakan adalah toast atau popup di sudut kanan atas

            // Masing-masing modal akan dibagi 2
            // 2. Modal yang berhuungan dengan pesan akan diberi kode nomor (flashdata1, flashdata2, flasdata3, dan seterusnya)
            // 1. Modal yang berhubungan dengan elemen akan diberi kode huruf (flashdata_a, flashdata_b, flasdata_c, dan seterusnya)

            // Jika flashdata memiliki pesan atau fungsi, maka akan ditambahakan _msg1 atau _func1
            // flashdata1_msg1, flashdata_a_func1

            // Flashdata yang berhubungan dengan pesan

            // Authentication Flashdatas
            'v_flashdata1' => 'pesan',
            'v_flashdata1_msg1' => '',
            'v_flashdata1_msg2' => '',
            'v_flashdata_a' => 'panggil',
            'v_flashdata_a_func1' => '$("#element").toast("show")',

            // Pesan di bawah ini sudah boleh diubah
            'v6_flashdata1_msg1' => 'Selamat datang ' . $this->session->userdata($base_url . $tabel9_field6) . ' ' . $this->session->userdata($base_url . $tabel9_field2) . '!',
            'tabel8_v_flashdata1_msg2' => 'Ayo kita lanjutkan ke pemesanan, ' . $this->session->userdata($base_url . $tabel9_field6) . ' ' . $this->session->userdata($base_url . $tabel9_field2) . '!',

            'tabel4_v_flashdata1_msg_-1' => $tabel9_field4 . ' salah!',
            'tabel4_v_flashdata1_msg_0' => $tabel9_field3 . ' tidak tersedia!',
            'tabel9_v_flashdata1_msg_-1' => $tabel9_field4 . ' salah!',
            'tabel9_v_flashdata1_msg_0' => $tabel9_field3 . ' tidak tersedia!',


            // Data Manupulation Flashdatas
            'v_flashdata3' => 'pesan_tambah',
            'v_flashdata3_msg1' => '',
            'v_flashdata3_msg2' => '',
            'v_flashdata_c' => 'tambah',
            'v_flashdata_c_func1' => '$(".tambah").modal("show")',
            'tabel2_v_flashdata3_msg_1' => '',
            // 'tabel3_v_flashdata3_msg_1' => $tabel3_field4_alias . ' ' . $tabel3_alias . ' tidak bisa diupload',
            'tabel11_v_flashdata3_msg_1' => '',
            'tabel12_v_flashdata3_msg_1' => $tabel12_field3_alias . ' ' . $tabel12_alias . ' tidak bisa diupload',
            'tabel13_v_flashdata3_msg_1' => $tabel13_field4_alias . ' ' . $tabel13_alias . ' tidak bisa diupload',
            'tabel4_v_flashdata3_msg_1' => 'Konfirmasi ' . $tabel9_field4 . ' tidak sesuai!',
            'tabel4_v_flashdata3_msg_2' => $tabel9_field3 . 'telah digunakan!',
            'tabel9_v_flashdata3_msg_1' => 'Konfirmasi ' . $tabel9_field4 . ' tidak sesuai!',
            'tabel9_v_flashdata3_msg_2' => $tabel9_field3 . 'telah digunakan!',

            'v_flashdata4' => 'pesan_ubah',
            'v_flashdata4_msg1' => '',
            'v_flashdata4_msg2' => '',
            'v_flashdata_d' => 'ubah',
            'v_flashdata_d_func1' => '$(".ubah").modal("show")',
            // 'tabel2_v_flashdata4_msg_1' => '',
            'tabel4_v_flashdata4_msg_1' => 'Konfirmasi ' . $tabel9_field4 . ' tidak sesuai!',
            'tabel4_v_flashdata4_msg_2' => $tabel9_field4 . ' lama salah!',
            'tabel4_v_flashdata4_msg_3' => 'Akun tidak tersedia!',
            'tabel9_v_flashdata4_msg_1' => 'Konfirmasi ' . $tabel9_field4 . ' tidak sesuai!',
            'tabel9_v_flashdata4_msg_2' => $tabel9_field4 . ' lama salah!',
            'tabel9_v_flashdata4_msg_3' => 'Akun tidak tersedia!',
            // 'tabel10_v_flashdata4_msg_1' => $tabel3_field4_alias . ' ' . $tabel3_alias . ' tidak bisa diupload',
            // 'tabel11_v_flashdata4_msg_1' => '',
            'tabel12_v_flashdata4_msg_1' => $tabel12_field3_alias . ' ' . $tabel12_alias . ' tidak bisa diupload',
            'tabel13_v_flashdata4_msg_1' => $tabel13_field4_alias . ' ' . $tabel13_alias . ' tidak bisa diupload',

            'v_flashdata5' => 'pesan_lihat',
            'v_flashdata5_msg1' => '',
            'v_flashdata5_msg2' => '',
            'v_flashdata_e' => 'lihat',
            'v_flashdata_e_func1' => '$(".lihat").modal("show")',

            'v_flashdata6' => 'pesan_cari',
            'v_flashdata6_msg1' => '',
            'v_flashdata6_msg2' => '',
            'v_flashdata_f' => 'cari',
            'v_flashdata_f_func1' => '$(".cari").modal("show")',

            'v_flashdata7' => 'pesan_maintenance',
            'v_flashdata7_msg1' => '',
            'v_flashdata7_msg2' => '',
            'v_flashdata_g' => 'maintenance',
            'v_flashdata_g_func1' => '$(".maintenance").modal("show")',

            'v_flashdata8' => 'pesan_cleaning',
            'v_flashdata8_msg1' => '',
            'v_flashdata8_msg2' => '',
            'v_flashdata_h' => 'clean',
            'v_flashdata_h_func1' => '$(".clean").modal("show")',

            'v_flashdata11' => 'pesan_favicon',
            'v_flashdata11_msg1' => '',
            'v_flashdata11_msg2' => '',
            'v_flashdata_k' => 'favicon',
            'v_flashdata_k_func1' => '$(".favicon").modal("show")',
            'tabel7_v_flashdata11_msg_1' => $tabel7_field3_alias . ' ' . $tabel7_alias . ' tidak bisa diupload',

            'v_flashdata12' => 'pesan_logo',
            'v_flashdata12_msg1' => '',
            'v_flashdata12_msg2' => '',
            'v_flashdata_l' => 'logo',
            'v_flashdata_l_func1' => '$(".logo").modal("show")',
            'tabel7_v_flashdata12_msg_1' => $tabel7_field4_alias . ' ' . $tabel7_alias . ' tidak bisa diupload',

            'v_flashdata13' => 'pesan_foto',
            'v_flashdata13_msg1' => '',
            'v_flashdata13_msg2' => '',
            'v_flashdata_m' => 'foto',
            'v_flashdata_m_func1' => '$(".foto").modal("show")',
            'tabel7_v_flashdata13_msg_1' => $tabel7_field5_alias . ' ' . $tabel7_alias . ' tidak bisa diupload',

            'v_flashdata15' => 'pesan_event',
            'v_flashdata15_msg1' => '',
            'v_flashdata15_msg2' => '',
            'v_flashdata_o' => 'event',
            'v_flashdata_o_func1' => '$("#event").modal("show")',

            // Form Submission Flashdatas
            'v_flashdata2' => 'notifikasi',
            'v_flashdata2_msg1' => '',
            'v_flashdata2_msg2' => '',
            'v_flashdata_b' => 'modal',
            'v_flashdata_b_func1' => '$(".password").modal("show")',

            // Notification and alert Flashdatas
            'v_flashdata14' => 'pesan_quickTour',
            'v_flashdata14_msg1' => "Anda hanya akan mendapatkan quick tour ini sebanyak 2 kali",
            'v_flashdata14_msg2' => '',
            'v_flashdata_n' => 'quickTour',
            'v_flashdata_n_func1' => '$("#quickTour").modal("show")',

            // Special user interaction Flashdatas
            'v_flashdata9' => 'pesan_book',
            'v_flashdata9_msg1' => '',
            'v_flashdata9_msg2' => '',
            'v_flashdata_i' => 'book',
            'v_flashdata_i_func1' => '$(".book").modal("show")',

            // 'v_flashdata10' => 'pesan_' . $tabel10_field6,
            // 'v_flashdata10_msg1' => '',
            // 'v_flashdata10_msg2' => '',
            // 'v_flashdata_j' => $tabel10_field6,
            // 'v_flashdata_j_func1' => '$(".' . $tabel10_field6 . '").modal("show")',
            // 'tabel10_v_flashdata1_msg_7' => 'Selamat! Anda sudah bisa mengunjungi website!',
            // 'tabel10_v_flashdata1_msg_8' => 'Anda belum bisa mengunjungi website!',
            // 'tabel10_v_flashdata1_msg_9' => $tabel10_alias . ' tidak valid!',


            // Semua yang menggunakan flashdata1: Menampilkan pesan
            // 'tabel1_v_flashdata1_msg_1' => 'Data ' . $tabel1_alias . ' berhasil disimpan!',
            // 'tabel1_v_flashdata1_msg_2' => 'Data ' . $tabel1_alias . ' gagal disimpan!',
            // 'tabel1_v_flashdata1_msg_3' => 'Data ' . $tabel1_alias . ' berhasil diubah!',
            // 'tabel1_v_flashdata1_msg_4' => 'Data ' . $tabel1_alias . ' gagal diubah!',
            // 'tabel1_v_flashdata1_msg_5' => 'Data ' . $tabel1_alias . ' berhasil dihapus!',
            // 'tabel1_v_flashdata1_msg_6' => 'Data ' . $tabel1_alias . ' gagal dihapus!',

            // 'tabel2_v_flashdata1_msg_1' => 'Data ' . $tabel2_alias . ' berhasil disimpan!',
            // 'tabel2_v_flashdata1_msg_2' => 'Data ' . $tabel2_alias . ' gagal disimpan!',
            // 'tabel2_v_flashdata1_msg_3' => 'Status ' . $tabel2_alias . ' berhasil diubah!',
            // 'tabel2_v_flashdata1_msg_4' => 'Status ' . $tabel2_alias . ' gagal diubah!',
            // 'tabel2_v_flashdata1_msg_5' => 'Data ' . $tabel2_alias . ' berhasil dihapus!',
            // 'tabel2_v_flashdata1_msg_6' => 'Data ' . $tabel2_alias . ' gagal dihapus!',

            // 'tabel3_v_flashdata1_msg_1' => 'Data ' . $tabel3_alias . ' berhasil disimpan!',
            // 'tabel3_v_flashdata1_msg_2' => 'Data ' . $tabel3_alias . ' gagal disimpan!',
            // 'tabel3_v_flashdata1_msg_3' => 'Data ' . $tabel3_alias . ' berhasil diubah!',
            // 'tabel3_v_flashdata1_msg_4' => 'Data ' . $tabel3_alias . ' gagal diubah!',
            // 'tabel3_v_flashdata1_msg_5' => 'Data ' . $tabel3_alias . ' berhasil dihapus!',
            // 'tabel3_v_flashdata1_msg_6' => 'Data ' . $tabel3_alias . ' gagal dihapus!',

            'tabel4_v_flashdata1_msg_1' => 'Data ' . $tabel4_alias . ' berhasil disimpan!',
            'tabel4_v_flashdata1_msg_2' => 'Data ' . $tabel4_alias . ' gagal disimpan!',
            'tabel4_v_flashdata1_msg_3' => 'Data ' . $tabel4_alias . ' berhasil diubah!',
            'tabel4_v_flashdata1_msg_4' => 'Data ' . $tabel4_alias . ' gagal diubah!',
            'tabel4_v_flashdata1_msg_5' => 'Data ' . $tabel4_alias . ' berhasil dihapus!',
            'tabel4_v_flashdata1_msg_6' => 'Data ' . $tabel4_alias . ' gagal dihapus!',

            'tabel5_v_flashdata1_msg_1' => 'Data ' . $tabel5_alias . ' berhasil disimpan!',
            'tabel5_v_flashdata1_msg_2' => 'Data ' . $tabel5_alias . ' gagal disimpan!',
            'tabel5_v_flashdata1_msg_3' => 'Data ' . $tabel5_alias . ' berhasil diubah!',
            'tabel5_v_flashdata1_msg_4' => 'Data ' . $tabel5_alias . ' gagal diubah!',
            'tabel5_v_flashdata1_msg_5' => 'Data ' . $tabel5_alias . ' berhasil dihapus!',
            'tabel5_v_flashdata1_msg_6' => 'Data ' . $tabel5_alias . ' gagal dihapus!',

            'tabel6_v_flashdata1_msg_1' => 'Data ' . $tabel6_alias . ' berhasil disimpan!',
            'tabel6_v_flashdata1_msg_2' => 'Data ' . $tabel6_alias . ' gagal disimpan!',
            'tabel6_v_flashdata1_msg_3' => 'Data ' . $tabel6_alias . ' berhasil diubah!',
            'tabel6_v_flashdata1_msg_4' => 'Data ' . $tabel6_alias . ' gagal diubah!',
            'tabel6_v_flashdata1_msg_5' => 'Data ' . $tabel6_alias . ' berhasil dihapus!',
            'tabel6_v_flashdata1_msg_6' => 'Data ' . $tabel6_alias . ' gagal dihapus!',

            'tabel7_v_flashdata1_msg_1' => 'Data ' . $tabel7_alias . ' berhasil disimpan!',
            'tabel7_v_flashdata1_msg_2' => 'Data ' . $tabel7_alias . ' gagal disimpan!',
            'tabel7_v_flashdata1_msg_3' => 'Data ' . $tabel7_alias . ' berhasil diubah!',
            'tabel7_v_flashdata1_msg_4' => 'Data ' . $tabel7_alias . ' gagal diubah!',
            'tabel7_v_flashdata1_msg_5' => 'Data ' . $tabel7_alias . ' berhasil dihapus!',
            'tabel7_v_flashdata1_msg_6' => 'Data ' . $tabel7_alias . ' gagal dihapus!',
            'tabel7_v_flashdata1_msg_7' => $tabel7_field3_alias . ' ' . $tabel7_field2_alias . ' berhasil diubah!',
            'tabel7_v_flashdata1_msg_8' => $tabel7_field3_alias . ' ' . $tabel7_field2_alias . ' gagal diubah!',
            'tabel7_v_flashdata1_msg_9' => $tabel7_field4_alias . ' ' . $tabel7_field2_alias . ' berhasil diubah!',
            'tabel7_v_flashdata1_msg_10' => $tabel7_field4_alias . ' ' . $tabel7_field2_alias . ' gagal diubah!',
            'tabel7_v_flashdata1_msg_11' => $tabel7_field5_alias . ' ' . $tabel7_field2_alias . ' berhasil diubah!',
            'tabel7_v_flashdata1_msg_12' => $tabel7_field5_alias . ' ' . $tabel7_field2_alias . ' gagal diubah!',
            'tabel7_v_flashdata1_msg_13' => $tabel7_field12_alias . ' ' . $tabel7_field2_alias . ' berhasil diubah!',
            'tabel7_v_flashdata1_msg_14' => $tabel7_field12_alias . ' ' . $tabel7_field2_alias . ' gagal diubah!',

            'tabel8_v_flashdata1_msg_1' => 'Data ' . $tabel8_alias . ' berhasil disimpan!',
            'tabel8_v_flashdata1_msg_2' => 'Data ' . $tabel8_alias . ' gagal disimpan!',
            'tabel8_v_flashdata1_msg_3' => 'Data ' . $tabel8_alias . ' berhasil diubah!',
            'tabel8_v_flashdata1_msg_4' => 'Data ' . $tabel8_alias . ' gagal diubah!',
            'tabel8_v_flashdata1_msg_5' => 'Data ' . $tabel8_alias . ' berhasil dihapus!',
            'tabel8_v_flashdata1_msg_6' => 'Data ' . $tabel8_alias . ' gagal dihapus!',
            'tabel8_v_flashdata1_msg_7' => 'Status ' . $tabel8_alias . ' berhasil diubah!',
            'tabel8_v_flashdata1_msg_8' => 'Status ' . $tabel8_alias . ' gagal diubah!',

            'tabel9_v_flashdata1_msg_1' => 'Data ' . $tabel9_alias . ' berhasil disimpan!',
            'tabel9_v_flashdata1_msg_2' => 'Data ' . $tabel9_alias . ' gagal disimpan!',
            'tabel9_v_flashdata1_msg_3' => 'Data ' . $tabel9_alias . ' berhasil diubah!',
            'tabel9_v_flashdata1_msg_4' => 'Data ' . $tabel9_alias . ' gagal diubah!',
            'tabel9_v_flashdata1_msg_5' => 'Data ' . $tabel9_alias . ' berhasil dihapus!',
            'tabel9_v_flashdata1_msg_6' => 'Data ' . $tabel9_alias . ' gagal dihapus!',

            // 'tabel10_v_flashdata1_msg_1' => 'Data ' . $tabel10_alias . ' berhasil disimpan!',
            // 'tabel10_v_flashdata1_msg_2' => 'Data ' . $tabel10_alias . ' gagal disimpan!',
            // 'tabel10_v_flashdata1_msg_3' => 'Data ' . $tabel10_alias . ' berhasil diubah!',
            // 'tabel10_v_flashdata1_msg_4' => 'Data ' . $tabel10_alias . ' gagal diubah!',
            // 'tabel10_v_flashdata1_msg_5' => 'Data ' . $tabel10_alias . ' berhasil dihapus!',
            // 'tabel10_v_flashdata1_msg_6' => 'Data ' . $tabel10_alias . ' gagal dihapus!',

            // 'tabel11_v_flashdata1_msg_1' => 'Data ' . $tabel11_alias . ' berhasil disimpan!',
            // 'tabel11_v_flashdata1_msg_2' => 'Data ' . $tabel11_alias . ' gagal disimpan!',
            // 'tabel11_v_flashdata1_msg_3' => 'Data ' . $tabel11_alias . ' berhasil diubah!',
            // 'tabel11_v_flashdata1_msg_4' => 'Data ' . $tabel11_alias . ' gagal diubah!',
            // 'tabel11_v_flashdata1_msg_5' => 'Data ' . $tabel11_alias . ' berhasil dihapus!',
            // 'tabel11_v_flashdata1_msg_6' => 'Data ' . $tabel11_alias . ' gagal dihapus!',

            'tabel12_v_flashdata1_msg_1' => 'Data ' . $tabel12_alias . ' berhasil disimpan!',
            'tabel12_v_flashdata1_msg_2' => 'Data ' . $tabel12_alias . ' gagal disimpan!',
            'tabel12_v_flashdata1_msg_3' => 'Data ' . $tabel12_alias . ' berhasil diubah!',
            'tabel12_v_flashdata1_msg_4' => 'Data ' . $tabel12_alias . ' gagal diubah!',
            'tabel12_v_flashdata1_msg_5' => 'Data ' . $tabel12_alias . ' berhasil dihapus!',
            'tabel12_v_flashdata1_msg_6' => 'Data ' . $tabel12_alias . ' gagal dihapus!',

            'tabel13_v_flashdata1_msg_1' => 'Data ' . $tabel13_alias . ' berhasil disimpan!',
            'tabel13_v_flashdata1_msg_2' => 'Data ' . $tabel13_alias . ' gagal disimpan!',
            'tabel13_v_flashdata1_msg_3' => 'Data ' . $tabel13_alias . ' berhasil diubah!',
            'tabel13_v_flashdata1_msg_4' => 'Data ' . $tabel13_alias . ' gagal diubah!',
            'tabel13_v_flashdata1_msg_5' => 'Data ' . $tabel13_alias . ' berhasil dihapus!',
            'tabel13_v_flashdata1_msg_6' => 'Data ' . $tabel13_alias . ' gagal dihapus!',
        );
    }
}
